name: Publish jinja to pypi

on:
  workflow_dispatch:
  push:
    tags: ["tree-sitter-jinja-*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  pypi-jinja:
    uses: cathaysia/tree-sitter-workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      working-directory: tree-sitter-jinja
