name: Publish jinja_inline to pypi

on:
  workflow_dispatch:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  pypi-jinja:
    uses: cathaysia/tree-sitter-workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      working-directory: tree-sitter-jinja
  pypi-jinja_inline:
    uses: cathaysia/tree-sitter-workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      working-directory: tree-sitter-jinja_inline
